### ISSUE TITLE
Quoted forum posts generate wrong links

### ISSUE THREAD

**Issue by koukoI** [goodguygregg-dev/emp-checker-ggg#1]
This bug carries from the old version:

Clicking the '>' in a quote label lets you visit the source link. The links generated by the script get formatted as torrent comments regardless of them being forum posts or collage/request comments. I am aware collage comments are currently bugged site wise.

Example with a quoted forum post:

/forum/thread/113873?postid=2868645#post2868645 
[quote=username,**t2868645**,2868645]yadda yadda[/quote] <- result
[quote=username,**f113873**,2868645]yadda yadda[/quote] <- expected

**Comment by goodguygregg-dev** [comment]
apparently it was not resolved

**Comment by koukoI** [comment]
All that was fixable has been fixed. Collage comments are still bugged sitewise. Closing this.
